---
# tasks file for copy_files
- name: Synchronization of src on the control machine to dest on the remote hosts
  synchronize:
      mode: push
      src: "{{ source_folder }}"
      dest: "{{ dest_folder }}"
  notify:
      - Restart Apache RedHat
      - Restart Apache Debian
