---
# tasks file for copy_files
- name: Create folder for app
  file: path={{ dest_folder }}/flask_app state=directory

- name: Synchronization of src on the control machine to dest on the remote hosts
  synchronize:
      mode: push
      src: "{{ source_folder }}"
      dest: "{{ dest_folder }}"
  notify:
      - Restart Apache RedHat
      - Restart Apache Debian
