---
- name: Test connection to my servers
  hosts: "{{ MYHOSTS }}"
  become: yes

  roles:
    - check_ping
    - { role: installing_software, when: ansible_system == 'Linux' }
    - add_user_
    - venv_inst
    - copy_files
#    - wsgi_apache_cfg
    - ssh_authorized
    - conf_ufw

  tasks:

  - name: start wsgi
    command: a2enmod wsgi

  - name: Restart Apache
    service: name=apache2 state=restarted
#  - name: start venv
#    command: python3 venv venv
