---
- block: # ------Block for RedHat------

  - name: Update
    yum:
      update: yes

  - name: install curl
    yum: name=curl state=latest

  - name: Install UFW
    yum: name=ufw state=latest

  - name: Install Apache Web server for RedHat
    yum: name=httpd state=latest

  - name: Start Apache Web Server service for RedHat
    service: name=httpd state=started enabled=yes

  - name: Instal Python3
    yum: name=rh-python37 state=latest

  - name: Install mod_wsgi
    yum: name=mod-wsgi state=latest
    notify:
      - Restart Apache RedHat

  - name: Install PIP, virtualenv and other
    yum: name={{ item }} state=latest
    loop:
      - rh-python37-python-tools
      - rh-python37-pip
      - rh-python37-virtualenv
      - rh-python37-PyYAML

  - name: Install rsync
    yum: name=rsync state=latest

  when: ansible_os_family == "RedHat"

- block: # ------Block for Debian-----

  - name: Update Deb
    apt:
      update_cache: yes

  - name: Install curl
    apt: name=curl state=latest

  - name: Install UFW
    apt: name=ufw state=latest

  - name: Install Apache Web server for Debian
    apt: name=apache2 state=latest

  - name: Start Apache Web Server Debian
    service: name=apache2 state=started enabled=yes

  - name: Instal Python3
    apt: name=python3 state=latest

  - name: Install mod_wsgi
    apt: name=libapache2-mod-wsgi-py3 state=latest
    notify:
      - Restart Apache Debian

  - name: Install PIP, virtualenv
    apt: name={{ item }} state=latest
    loop:
      - python3-pip
      - python3-virtualenv

  - name: Install rsync
    apt: name=rsync state=latest

  when: ansible_os_family == "Debian"

