---
# tasks file for conf_ufw

- name: 15a-Copy file rule for flask
  copy:
     src: ./files/rule_flask
     dest: /etc/ufw/applications.d
     owner: root
     group: root
     mode: '0644'
  notify:
     - Restart UFW

- name: 15-added rules of UFW
  community.general.ufw:
     rule: allow
     name: '{{ item }}'
  loop:
     - "WWW Full"
     - "OpenSSH"
     - "flask_emoji"
  notify:
       - Restart UFW
